### ISSUE TITLE
Creating a new deck can override an existing deck

### ISSUE THREAD

**Issue by sagea** [sagenate24/Flash-Cards#1]
**Bug Description:**
If you create a new deck with the same title as an existing deck, the existing deck gets overwritten.

**Repro Steps:**
1. Create a new deck "FooBar"
2. Add a card to that deck
3. Goto the home page. You will see the "FooBar" deck has one card.
4. Create another deck with the same name "FooBar"
5. Goto the home page. The "FooBar" deck is now empty.

**Comment by sagenate24** [comment]
Issue Resolved: New deck can not be created if the title matches an existing deck title.

Thanks!
